### ISSUE TITLE
what is the source of the predictions?

### ISSUE THREAD

**Issue by LeagueLens** [Dusoye/fantasyfootball#1]
Hi 
Got a question and a suggession

Questions: 
What is the source of the predictions file used and how do you keep it updated. 

Suggession:
The suggested team is a bit poor and i think you'll need to add an option to chose the starting formation.  See below example

              name  pos team  price   xP  lineup  captain  vicecaptain
9         Trippier  DEF  NEW    6.0  5.2       1        0            0
7          Gabriel  DEF  ARS    6.0  4.6       1        0            0
8      Pedro Porro  DEF  TOT    5.5  4.2       1        0            0
5             Isak  FWD  NEW    8.5  5.9       1        0            0
6             Wood  FWD  NOT    6.0  4.7       1        0            0
10            Pope   GK  NEW    5.0  3.9       1        0            0
0          M.Salah  MID  LIV   12.5  7.0       1        1            0
1             Saka  MID  ARS   10.0  6.8       1        0            1
2         Ødegaard  MID  ARS    8.5  5.8       1        0            0
3      B.Fernandes  MID  MUN    8.5  5.7       1        0            0
4              Eze  MID  CRY    7.0  4.7       1        0            0
11  Harwood-Bellis  DEF  SOT    4.0  1.4       0        0            0
12      Woolfenden  DEF  IPS    4.0  1.4       0        0            0
13        Jebbison  FWD  BOU    4.5  0.2       0        0            0
14          Lumley   GK  SOT    4.0  0.0       0        0            0

**Comment by Dusoye** [comment]
The source of the predicted points is currently from fantasyfootballscout but fplreview seems to be the best option. I won't be updating it for this season but may be something better in place for next season.

The starting formation is currently determined by whatever the optimiser thinks is best, but the optimiser is pretty simplified at the moment and only really uses the rules as it's constraints. Much more can be included such as adding a weighting to subs, a decay to future game weeks and also fixing a formation or starting players.
